name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Instala Conda e cria o env
      uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: environment.yml
          auto-activate-base: true
    - name: Ativa o conda
      uses: s-weigand/setup-conda@v1
    - name: Ativa o env  
      run: conda activate maua-dev-env



    - name: Runs tests
      run: pytest
    - name: Create coverage report
      run: |
        pytest --cov=./
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
